services:
  scraper:
    build: 
      context: ./fashion_crawler/
    ports:
      - "6800:6800"
    volumes:
      - ~/.aws:/root/.aws

  etl_pipeline:
    build:
      context: ./etl
    container_name: etl_pipeline
    volumes:
      - ~/.aws:/root/.aws
    env_file:
      - .env

  training:
    build:
      context: ./model_training
    command: python model_trainer.py
    volumes:
      - ~/.aws:/root/.aws:ro
    env_file:
      - .env